### ISSUE TITLE
Bug: Addons get removed from car after returning home through pause menu.

### ISSUE THREAD

**Issue by itsbudyn** [Jalopy-Mods/LaikaAddons#1]
### Description
Laika Addons are no longer applied after choosing "Return Home".
### Steps to reproduce
- At any point of the game, pause and return to home
### Expected result
The Laika addons remain applied.
### Actual result
Laika returns to vanilla (no turn signals, moved high beams switch etc.).
### Screenshots/Video
[Video recording](https://streamable.com/udiztk)
### Environment
- **OS**: Windows 11 23H2 (22631.2861)
- **Game version**: 1.105 (Steam)
- **JaLoader version**: 2.0.1
- **Additional mods**:
  - FogLight 1.0
  - MazdaEngine 1.1.1
  - Spoiler 1.0
  - RearBullbar 1.0

**Comment by theLeaxx** [comment]
This is a JaLoader issue, it will be fixed in the upcoming 3.0.0 release.
